import { GoogleGenAI, Modality } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const buildPrompt = (productName: string, productDescription: string): string => {
  const descriptionText = productDescription 
    ? `\n**User Instructions:**\n${productDescription}` 
    : '';

  return `
**TASK: DIRECT IMAGE COMPOSITE**

You will be given two images:
1.  An image of a product, '${productName}'.
2.  An image of an empty bowl.

**ABSOLUTE RULE: YOU MUST NOT CHANGE THE PRODUCT IMAGE.**
Your task is to perform a direct 'copy and paste' operation.

1.  **SELECT & COPY:** Select a portion of the product from the product image.
2.  **PASTE:** Paste the copied, **unaltered** product portion directly into the bowl from the bowl image.
3.  **NO MODIFICATION:** Do not generate, enhance, repaint, or change the color, texture, or lighting of the product pixels in any way. Treat it as a fixed object.
4.  **SHADOWS ONLY:** The only generative work you are allowed to do is add realistic shadows **inside the bowl** cast *by* the product. These shadows must match the existing lighting of the bowl image.
5.  **BACKGROUND:** The final image must have a pure, solid white (#FFFFFF) background, consistent with the bowl image.
6.  **BOWL:** Do not change the bowl.

**Final Output:** A high-resolution PNG image with a 1:1 aspect ratio, showing the original, unchanged product placed realistically inside the bowl.
${descriptionText}
  `;
};


export const generateProductPhotoFromImage = async (
    productImageData: {mimeType: string, data: string},
    bowlImageData: {mimeType: string, data: string},
    productName: string,
    productDescription: string
  ): Promise<string> => {
  const prompt = buildPrompt(productName, productDescription);

  const bowlImagePart = {
    inlineData: {
      mimeType: bowlImageData.mimeType,
      data: bowlImageData.data,
    },
  };
  
  const productImagePart = {
    inlineData: {
      mimeType: productImageData.mimeType,
      data: productImageData.data,
    },
  };

  const textPart = {
    text: prompt,
  };

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image-preview',
      contents: {
        parts: [bowlImagePart, productImagePart, textPart],
      },
      config: {
        responseModalities: [Modality.IMAGE, Modality.TEXT],
      },
    });

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        const base64ImageBytes = part.inlineData.data;
        return `data:${part.inlineData.mimeType};base64,${base64ImageBytes}`;
      }
    }
    
    // If no image part is found
    throw new Error("No image was generated by the API.");

  } catch (error) {
    console.error("Error calling Gemini API:", error);
    throw new Error("Failed to generate image from Gemini API.");
  }
};